### ISSUE TITLE
Bug with 

### ISSUE THREAD

**Issue by likeagency** [shadimanna/dhl-logistic-services-for-woocommerce#10]
Hey there, a bug appeared in the DHL Label Creator when the customer wanted to create one sending to Switzerland. 
Bug message: 
SOAP-ERROR: Encoding: object has no 'countryCodeOrigin" property - see error attached
https://www.dropbox.com/s/nq7i9g92qzmzora/chrome_2018-07-19_12-58-49.png?dl=0

**Comment by shadimanna** [comment]
This is related to the field within the product->shipping field "Country of Manufacture (DHL)" I believe.  This field needs to be set for cross-border shipments, please confirm.

**Comment by likeagency** [comment]
So each product need to have this set up here:
https://www.dropbox.com/s/s2105qt1pmi8w98/chrome_2018-07-23_14-46-50.png?dl=0 - to make product work?

**Comment by shadimanna** [comment]
Yes
