### ISSUE TITLE
Problems creating PDF

### ISSUE THREAD

**Issue by Willautzkat** [shadimanna/dhl-logistic-services-for-woocommerce#178]
When I click the "Create Label" button, I only get an empty HTML object/file. You can see the path on the screen.

<img width="2147" alt="screen3" src="https://github.com/shadimanna/dhl-logistic-services-for-woocommerce/assets/134268563/1a1534a4-33b5-4a54-898f-398b59441370">
<img width="249" alt="screen2" src="https://github.com/shadimanna/dhl-logistic-services-for-woocommerce/assets/134268563/8426fc01-3c89-4392-b4ea-0bc9e2379e71">
<img width="2152" alt="screen1" src="https://github.com/shadimanna/dhl-logistic-services-for-woocommerce/assets/134268563/0ceb2fc1-558b-4007-a285-cadea51164bf">

**Comment by Abdalsalaam** [comment]
Hi @Willautzkat , can you refresh the permalinks settings ? Please make sure to choose any structure other than the default

**Comment by Willautzkat** [comment]
Thanks very much! That solved my problem.

**Comment by Willautzkat** [comment]
Thank you
