### ISSUE TITLE
PHP Fatal error at WordPress Initialization 

### ISSUE THREAD

**Issue by verenaroe** [shadimanna/dhl-logistic-services-for-woocommerce#186]
I copied Code from my Theme to a separate Plugin.

I do this at the very beginning of my Plugin code:

```php
// Load the WordPress library.
require_once __DIR__ . '/../../../wp-load.php';
```

When it's running I get the following error:

```
[05-Jun-2023 12:21:46 UTC] PHP Fatal error:  Uncaught Error: Class 'PR\DHL\Utils\API_Utils' not found in /app/wordpress/wp-content/plugins/dhl-for-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-paket.php:22
Stack trace:
#0 /app/wordpress/wp-content/plugins/dhl-for-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-factory.php(52): PR_DHL_API_Paket->__construct('DE')
#1 /app/wordpress/wp-content/plugins/dhl-for-woocommerce/pr-dhl-woocommerce.php(496): PR_DHL_API_Factory::make_dhl('DE')
#2 /app/wordpress/wp-content/plugins/dhl-for-woocommerce/pr-dhl-woocommerce.php(282): PR_DHL_WC->get_dhl_factory()
#3 /app/wordpress/wp-content/plugins/dhl-for-woocommerce/pr-dhl-woocommerce.php(228): PR_DHL_WC->get_pr_dhl_wc_product()
#4 /app/wordpress/wp-includes/class-wp-hook.php(308): PR_DHL_WC->init('')
#5 /app/wordpress/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#6 /app/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#7 /app/wordpress/wp-settings.php(623): do_action('init')
#8 /app/wordpress/wp-config.php(88): require_onc in /app/wordpress/wp-content/plugins/dhl-for-woocommerce/includes/pr-dhl-api/class-pr-dhl-api-paket.php on line 22
```

As soon as I deactivate the plugin there's no error.

Uninstall and reinstall the newest version of the plugin didn't fixed the error.
WordPress Version: 6.2.2

**Comment by Abdalsalaam** [comment]
Hi @verenaroe , do you have a staging environment ? can you share an access to our email "dhlsupport [at] progressusmarketing.com"

thank you!

**Comment by verenaroe** [comment]
Thank you very much for your fast reply! 

Invitation from the staging environment sent to dhlsupport [at] progressusmarketing.com

Here is the page to see the error message:
https://cbgb.eat-this.org/wp-content/plugins/steady-connect/steady_callback.php

**Comment by Abdalsalaam** [comment]
@verenaroe Thank you! we will check it and let you know.

**Comment by verenaroe** [comment]
I think our autoload files in the plugin are causing this. I will have a look at it and let you know.
