### ISSUE TITLE
PHP Warnings in latest Version

### ISSUE THREAD

**Issue by masteradhoc** [shadimanna/dhl-logistic-services-for-woocommerce#188]
Two small Warnings when using the Plugin on PHP 8.0

2023/06/12 13:49:09 [error] 12975#12975: *287071 FastCGI sent in stderr: "

PHP message: PHP Warning: Attempt to read property "items" on string in /home/wp/disk/wordpress/wp-content/plugins/dhl-for-woocommerce/includes/REST_API/Parcel_DE/Client.php on line 446

PHP message: PHP Warning: foreach() argument must be of type array|object, null given in /home/wp/disk/wordpress/wp-content/plugins/dhl-for-woocommerce/includes/REST_API/Parcel_DE/Client.php on line 446

**Comment by Abdalsalaam** [comment]
Hi @masteradhoc , thank you for reporting this, it will be fixed in the next release
