### ISSUE TITLE
issue with dezimal divider (komma and point)

### ISSUE THREAD

**Issue by DinserDLUXE** [shadimanna/dhl-logistic-services-for-woocommerce#216]
Since the last update the plugin has issues when I change the weight manually.
My standard dividers are point for thousend (1.000) and komma for dezimal (1,00)
I changed the settings in woocommers to point for both but now it makes strange things.
a package with 0,13kg shows now 5.375kg, for example.

**Comment by Abdalsalaam** [comment]
Hello @DinserDLUXE 
We released v3.6.9 to fix this issue, update the plugin to the latest version and check it please
