### ISSUE TITLE
No translation template for the "dhl-for-woocommerce"

### ISSUE THREAD

**Issue by kokila-HWA** [shadimanna/dhl-logistic-services-for-woocommerce#22]
I got "No translation template for the "dhl-for-woocommerce"" message when I creating a new language from Loco Translate. Please help me to solve this issue.  Thank you

**Comment by shadimanna** [comment]
It seems you have not assigned the pot template.  Please go to : 

"Loco Translate >> Plugins". Click "DHL for WooCommerce".

Then Click "Overview" tab. you will see "Template file" textbox. Input this path as the value :
"dhlpwoocommerce/languages/dhlpwc.pot"

**Comment by shadimanna** [comment]
Closing
