### ISSUE TITLE
CN23 Document Includes Refunded Order Items

### ISSUE THREAD

**Issue by ed-at-protectli** [shadimanna/dhl-logistic-services-for-woocommerce#223]
Using plugin version 3.6.5, tested with both sandbox/production and both SOAP/REST APIs.

When requesting a shipment to the UK (where a CN23 document is generated), line items from the order that have been fully refunded are not omitted from the form.

To reproduce:

1. Create an order with multiple line items to be shipped to UK with a value over 270 GBP (so it meets CN23 requirements)
2. As an administrator, refund an entire line item
3. Attempt to generate a shipment label

Expected result:

* The generated forms should reflect the order in its current state

Actual result:

* The generated forms have line items that were refunded, and as such, are not being shipped

Suggested resolution:

* All forms/labels/etc. should not include items that were refunded before label generation.

**Comment by Abdalsalaam** [comment]
Hello @ed-at-protectli 
thank you for reporting this issue, I'll check it and get back to you ASAP

**Comment by Abdalsalaam** [comment]
@ed-at-protectli  Fixed, update the plugin to the latest version and check it please.
