### ISSUE TITLE
Label Format/Label Size Options missing

### ISSUE THREAD

**Issue by alorbach** [shadimanna/dhl-logistic-services-for-woocommerce#25]
I am not able to configure many advanced options with german language settings. 
Like 'Label Format', 'Label Size'.

Or are they hidden somewhere in the admin panel?

**Comment by shadimanna** [comment]
These settings don't currently exist within the plugin.  If there is enough demand for this we can add it in future versions.

**Comment by alorbach** [comment]
Can you tell me if it can be changed hardcoded to aniother format? 
At the moment Din A4 labels are generated which are useless for most DHL Business customers. We need DL format (DHL Lables).

At the moment I have to create a lable, then login into dhl geschäftskunden portal and print the generate lable from there.

**Comment by shadimanna** [comment]
Unfortunately, this cannot be accomplished via the DHL Paket API.  However, DHL support seems to believe you can modify the settings in the business (www.dhl-geschaeftskundenportal.de) which might return a different format.  Please confirm with them.

**Comment by alorbach** [comment]
Its already set to Common Label, see screenshot with the business dhl:
![image](https://user-images.githubusercontent.com/1675286/51239486-d06c3380-1979-11e9-98ae-acb6c85b1f68.png)

**Comment by shadimanna** [comment]
Please reach out to DHL support as their API cannot control the format, as mentioned before.

**Comment by alorbach** [comment]
FYI: This appears to working with the current version now :)

**Comment by shadimanna** [comment]
Great, not sure what happened or why but glad it's working.
