### ISSUE TITLE
States dropdown not appearing for countries other than Vietnam

### ISSUE THREAD

**Issue by siliconforks** [shadimanna/dhl-logistic-services-for-woocommerce#35]
It seems that this plugin causes all states to be lost except those in Vietnam.  For example, if you go to the checkout page and select Vietnam as the country, you will get a dropdown with a list of all Vietnamese states, but if you select any other country (e.g., the United States), you will just get a text field for the state.

The problem is that `WC()->countries->get_states( $cc )` is returning `false` for any country other than Vietnam.  The filter function `add_vn_states` is supposed to add Vietnamese states to the array of states, but it instead replaces the entire array.  It appears that the file https://github.com/shadimanna/dhl-logistic-services-for-woocommerce/blob/master/pr-dhl-woocommerce/states/VN.php declares `$states` to be `global`, so this is a different variable from the local `$states` variable inside the function.

**Comment by shadimanna** [comment]
Thank you for adding this issue, we will get it fixed ASAP.

**Comment by shadimanna** [comment]
This is fixed in v1.4.2
