### ISSUE TITLE
WPML fix breaks admin links in multisite environment in non-WPML site

### ISSUE THREAD

**Issue by mklasen** [shadimanna/dhl-logistic-services-for-woocommerce#45]
Hi - We noticed that the WPML fix in `dhlpwoocommerce.php` breaks admin links in our environment. I haven't been able to reproduce this in a clean install, but can confirm that the site functions as intended when the fix is commented out.

Since the fix is only applicable for WPML it might be better to either wrap it in a`is_wpml_active` function, or to hook it into `wpml_loaded`. Both of these examples are suggestions and not solutions.

Looking forward to hear your thoughts,

https://github.com/shadimanna/dhl-logistic-services-for-woocommerce/blob/6034999164c96b2ed6f0cab9783aed1c3c355a84/pr-dhl-woocommerce/dhlpwoocommerce/dhlpwoocommerce.php#L54-L57

**Comment by mklasen** [comment]
Hi @shadimanna - can you check out the commit mentioned above?

**Comment by ShinCode** [comment]
Hi @mklasen , thanks for notifying us of this issue.
We've starting looking into the issue and we'll return with a proper resolution soon.

**Comment by mklasen** [comment]
Hi @ShinCode - Any update on this?

**Comment by mklasen** [comment]
Hi @ShinCode - I noticed the PR is closed. Is this issue resolved?

**Comment by shadimanna** [comment]
Closing
