### ISSUE TITLE
Issue with weights that are not full KGs

### ISSUE THREAD

**Issue by SeraphMcLight** [shadimanna/dhl-logistic-services-for-woocommerce#59]
When trying to generate a label with default settings where the weight is not rounded to a full KG number it returns the error:

Cannot convert string "5,5" to a double

this happens with any X,x - where in the weight field in this instance was 5500g - asides from the workaround to make sure it's a full KG (also interferes with Warenpost).

Is that a known issue?

**Comment by shadimanna** [comment]
Can you trying entering "5.5" instead?  I believe all decimals in the backend need to be with "."

**Comment by SeraphMcLight** [comment]
> Can you trying entering "5.5" instead? I believe all decimals in the backend need to be with "."

Hey, sorry for getting back to you a little late. Tried out with "." as decimal, it'll tell me decimals can only be "," and when using that it responds with using grams instead and not kgs.

**Comment by shadimanna** [comment]
Can we continue this conversation via email, please contact me at "dhlsupport [at] progressusmarketing.com” so I can review your site.

**Comment by SeraphMcLight** [comment]
Sure can do, will drop you a first contact now.
