### ISSUE TITLE
SOAP-ERROR: Encoding: object has no 'customsTariffNumber' property

### ISSUE THREAD

**Issue by BeastTeachGorilla** [shadimanna/dhl-logistic-services-for-woocommerce#60]
Dear Community,

I am running into the following Error: "SOAP-ERROR: Encoding: object has no 'customsTariffNumber' property".

As a german shop we got our first customer from Norway. Unfortunately the generating of the DHL-Label is not working with the Error above.

What field do we need to fill out ? I did not find a place anywhere.
A little help would be appreciated.

Thank you !

**Comment by shadimanna** [comment]
This field is the HS Code field that must be set for each product under the shipping tab.

**Comment by BeastTeachGorilla** [comment]
Hey shadimanna,

thank you for your help. Issue fixed, can be closed.
