### ISSUE TITLE
merge broken with php8

### ISSUE THREAD

**Issue by Avatarsia** [shadimanna/dhl-logistic-services-for-woocommerce#72]
Wenn ich eine reihe von Labels erstellen lasse kommt seit dem Update auf PHP8 dieser Fehler, die labels sind im Geschäftskundenportal korrekt hinterlegt. 

Ein Fehler vom Typ E_ERROR wurde in der Zeile 1047 der Datei /wordpress/wp-content/plugins/dhl-for-woocommerce/lib/PDFMerger/fpdf/fpdf.php verursacht. Fehlermeldung: Uncaught Error: Call to undefined function get_magic_quotes_runtime() in wordpress/wp-content/plugins/dhl-for-woocommerce/lib/PDFMerger/fpdf/fpdf.php:1047
Stack trace:
#0 wordpress/wp-content/plugins/dhl-for-woocommerce/lib/PDFMerger/fpdf/fpdf.php(81): FPDF->_dochecks()
#1/wordpress/wp-content/plugins/dhl-for-woocommerce/lib/PDFMerger/PDFMerger.php(80): FPDF->__construct()
#2 /wordpress/wp-content/plugins/dhl-for-woocommerce/includes/abstract-pr-dhl-wc-order.php(1211): PR_DHLlibPDFMergerPDFMerger->merge()
#3 /wordpress/wp-content/plugins/dhl-for-woocommerce/includes/abstract-pr-dhl-wc-order.php(1172): PR_DHL_WC_Order->merge_label_files_pdf()
#4 /wordpress/wp-content/plugins/dhl-for-woocommerce/includes/abstract-pr-dhl-wc-order.php(1089): PR_DHL_WC_Order->merge_label_files()
#5 /wordpress/wp-content/plugins/dhl-for-woocommerce/includes/abstract-pr-dhl-wc-order.php(915): PR_DHL_WC_Order->process_bulk_actions()
#6 /wordpress/wp-includes/class-wp-hook.php(303): PR_DHL_WC_Order->process_orders_bulk_actions()
#7 /wordpress/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#8 /wordpress/wp-includes/plugin.php(470): WP_Hook->do_action()
#9 /www/wordpress/wp-admin/admin.php(374): do_action()
#10 /wordpress/wp-admin/edit.php(10): require_once('...')
#11 {main}
thrown

Außerdem bitte ich um eine längeren Zeitraum für das abrufen der Merged Labels, diese brauchen zum teil ja recht lange zum erstellen, dann lässt man den rechner halt arbeiten.
Es ist ziemlich nervig das wenn man 15 minuten später kommt der Link abgelaufen ist.

**Comment by shadimanna** [comment]
We are looking into replacing the "PDF Merger" library with a new version. Thank you for your patience.

**Comment by shadimanna** [comment]
This issue has been fixed in the recent version.
