### ISSUE TITLE
No way to filter a WooCommerce order note visibility

### ISSUE THREAD

**Issue by ed-at-protectli** [shadimanna/dhl-logistic-services-for-woocommerce#75]
When a note visible to customers is added to a WooCommerce order, an email notification is sent to the customer if the "Customer Note" WooCommerce email is enabled. However, this is a global "send all notes" or "send no notes" setting within WooCommerce.

For our use case, we do not want an email sent to customers when the tracking information note is added, because we will send it in the "Order Completed" email.

This PR introduces filters to override the visibility of the WooCommerce notes inserted by the plugin. So, for my specific case, code like `add_filter( 'pr_shipping_dhl_send_tracking_note_to_customer', function() { return 0; }, 10, 1 );` will make the note type hidden from the customer, thus not triggering the email.

**Comment by shadimanna** [comment]
There is a setting to make the notes private in the Shipping > DHL Paket, did you try that?

**Comment by ed-at-protectli** [comment]
I missed this completely! Yes, this is essentially the same thing. PR closed.
