### ISSUE TITLE
Maps API not working

### ISSUE THREAD

**Issue by SeraphMcLight** [shadimanna/dhl-logistic-services-for-woocommerce#77]
currently have a couple issues with the map for packstation not showing at all.

The webconsole shows up two errors here:

`You have included the Google Maps JavaScript API multiple times on this page. This may cause unexpected errors.`

and

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'h')`

As for the first, I can only imagine that it could come as a problem with us having a map set on our contact page. Which in turn we had removed for testing purposes in case that was the issue. It wasn't.

As for the second error. That error actually does show our API key entered in the DHL Plugins settings.

We're currently at our wits end. And the documentation doesn't really help asides from hardcoded settings.

**Comment by shadimanna** [comment]
Can you test on a staging site by disabling different plugins to find out which is adding the maps as well?

**Comment by SeraphMcLight** [comment]
HI sorry for the very late response.

We've tried it with a testing environment and a completely clean installation with no plugins besides woocommerce and the DHL plugin. The error messages are what I thought were strange. Is there any chance you could take a look at it?

**Comment by shadimanna** [comment]
Are you using a default theme as well?

**Comment by SeraphMcLight** [comment]
Yes we've tried it with the default theme aswell. Do you know of any incompatibilities with certain server side software?

**Comment by shadimanna** [comment]
Is this still an issue @SeraphMcLight ?

**Comment by SeraphMcLight** [comment]
We've gotten a bit farther - now it's actually showing a map but it is rejecting the key stating that no key was provided even though we've entered a key in the settings. I guess I'd close this issue for now.
