### ISSUE TITLE
filter dhl_force_product for process_bulk_actions

### ISSUE THREAD

**Issue by andit** [shadimanna/dhl-logistic-services-for-woocommerce#87]
Hi Shadi,
will there comes an option to filter the dhl_force_product in the process_bulk_actions?
I would like to add a new bulk actions for different products, like one for "Warenpost", one for "Paket", ...
That would make the work with it much smoother and comfortable.

Best Regards

Andi

**Comment by shadimanna** [comment]
Is it not sufficient to use the "Domestic Default Service" and "International Default Service" setting?

**Comment by andit** [comment]
not really, we send several shipments via "Warenpost" for international AND domestic customers but also via "Paket" to national and international.
I think really great would be some words to how add a custom made bulk action. 
i.e. for me it would be very helpful to get a function like "generateLable($orderID, $dhlProduct)" or something similar
Would that be possible?
Or maybe a wordpress hook to filter the dhl_force_product in the process_bulk_actions so that i can manipulate the dhl_force_product  depends on the order, orderitems and shipping country

**Comment by andit** [comment]
Hi, any news in this topic?

**Comment by shadimanna** [comment]
You could extend this class `PR_DHL_WC_Order_Paket` and override the function `process_bulk_actions` to force products and options in the bulk actions.  You can see how this was done in the `PR_DHL_WC_Order_Ecomm` class for example.

**Comment by shadimanna** [comment]
Closing this one out.

**Comment by andit** [comment]
Hi @shadimanna,
sorry for the long delay.
I've tried now this:

`
add_filter( 'bulk_actions-edit-shop_order', 'register_dhl_bulk_actions' ); 
function register_dhl_bulk_actions($bulk_actions) {
  $bulk_actions['dhl_create_paket_labels'] = "Generate DHL Paket Label";
  $bulk_actions['dhl_create_warenpost_labels'] = "Generate DHL Warenpost Label";
  
  return $bulk_actions;
}

add_filter( 'handle_bulk_actions-edit-shop_order', 'dhl_bulk_action_handler', 10, 3 );
function dhl_bulk_action_handler( $redirect_to, $doaction, $post_ids ) {
	 
	if ($doaction == 'dhl_create_paket_labels') 
		{			
			$redirect_to = remove_query_arg( array( 'bulk_dhl_create_paket_labels'), $redirect_to );
			$post_ids_rev = array_reverse($post_ids);
			$orders_count = count($post_ids);
			
			$dhl_options_org = get_option("woocommerce_pr_dhl_paket_settings");
			$dhl_options = $dhl_options_org;
			
			$dhl_options['dhl_default_product_int'] = 'V53WPAK';
			$dhl_options['dhl_default_product_dom'] = 'V01PAK';
			
			update_option("woocommerce_pr_dhl_paket_settings", $dhl_options);

			foreach ( $post_ids_rev as $post_id ) 
				{
					generate_DHL_Label($post_id);
				}	
			
			update_option("woocommerce_pr_dhl_paket_settings", $dhl_options_org);
			
			$redirect_to = add_query_arg(
								'bulk_dhl_create_paket_labels',
								array( 'processed_count' => $orders_count,
								$redirect_to ));
		}
	elseif ($doaction == 'dhl_create_warenpost_labels') 
		{			
			$redirect_to = remove_query_arg( array( 'bulk_dhl_create_warenpost_labels'), $redirect_to );
			$post_ids_rev = array_reverse($post_ids);
			$orders_count = count($post_ids);
			
			$dhl_options_org = get_option("woocommerce_pr_dhl_paket_settings");
			$dhl_options = $dhl_options_org;
			
			$dhl_options['dhl_default_product_int'] = 'V66WPI';
			$dhl_options['dhl_default_product_dom'] = 'V62WP';
			
			update_option("woocommerce_pr_dhl_paket_settings", $dhl_options);
			
			foreach ( $post_ids_rev as $post_id ) 
				{
					generate_DHL_Label($post_id);
				}	
				
			update_option("woocommerce_pr_dhl_paket_settings", $dhl_options_org);
			
			$redirect_to = add_query_arg(
								'bulk_dhl_create_warenpost_labels',
								array( 'processed_count' => $orders_count,
								$redirect_to ));
		}
	
	else
		return $redirect_to;
	
	return $redirect_to;
}

add_action( 'admin_notices', 'dhl_bulk_action_admin_notice' ); 
function dhl_bulk_action_admin_notice() {
	if ( ! empty( $_REQUEST['bulk_dhl_create_paket_labels'] ) ) {
		$uebergabeparameter=$_REQUEST['bulk_dhl_create_paket_labels'];		
		$labels_count = intval($uebergabeparameter['processed_count']);
		printf( '<div id="message" class="updated fade">' .
		  _n( 'Es wurde %s Label erzeugt.',
			'Es wurden %s Label erzeugt.',
			$labels_count,
			'bulk_dhl_create_paket_labels'
		  ) . '</div>', $labels_count );
	}
	elseif ( ! empty( $_REQUEST['bulk_dhl_create_warenpost_labels'] ) ) {
		$uebergabeparameter=$_REQUEST['bulk_dhl_create_warenpost_labels'];		
		$labels_count = intval($uebergabeparameter['processed_count']);
		printf( '<div id="message" class="updated fade">' .
		  _n( 'Es wurde %s Label erzeugt.',
			'Es wurden %s Label erzeugt.',
			$labels_count,
			'bulk_dhl_create_warenpost_labels'
		  ) . '</div>', $labels_count );
	}
}
`

I just need a function that I can use as "generate_DHL_Label($post_id);".

Can you help here, how I can find a function to do it in this way?

Best Regards

Andi
