### ISSUE TITLE
Bulk DHL Create labels with premium

### ISSUE THREAD

**Issue by Worldrazor** [shadimanna/dhl-logistic-services-for-woocommerce#90]
Hello,

I’m using the ”DHL for WooCommerce” plugin v2.8.8 and when I’m trying to bulk create shipments it dosen’t put ”Premium” on the labels, so I end up without Premium for all the labels I’ve created. I have already checked the ”Premium default” in backend.

It works fine when I try to create each order individually, then the Premium is on be default.

WP and woocommerce is updated to the newest version. WP v.5.9.2 – Woocommerce V 6.3.1

Is there a fix for this?

And another question:
Is it possible for the tracking links to be for the English tracking DHL page that’s sent out to customers?

So instead of:
https://www.dhl.de/de/privatkunden/dhl-sendungsverfolgung.html?piececode=

Be:
https://www.dhl.de/en/privatkunden/dhl-sendungsverfolgung.html?piececode=

And the last thing: 

When I'm trying to create a label for Switzerland then it says: SOAP-ERROR: Encoding: object has no 'countryCodeOrigin' property

What do I have to do to fix this? I got country of origin on all my products.

**Comment by shadimanna** [comment]
I believe this issue has been fixed in the latest version of the plugin, correct?

**Comment by shadimanna** [comment]
Closing for now, please re-open if the issue persists.
