### ISSUE TITLE
Unable to enter Shipper Address

### ISSUE THREAD

**Issue by kitka** [shadimanna/dhl-logistic-services-for-woocommerce#92]
Hi, I am trying to add details for the Shipper Address in the screen WooCommerce > Settings > Shipping > DHL Express. I can't save the details I put in, as I am asked if I want to leave the page with unsaved changes.  

I can also see this alert at the top of the page: The DHL plugin is not supported in your store's "Base Location"

Any help would be appreciated. 
WordPress version 5.9.3
WooCommerce version 6.4.0
DHL for WooCommerce version 2.8.12

Thanks!
Kitka

**Comment by shadimanna** [comment]
DHL Express is not part of this plugin, so it must be the wrong repo.

**Comment by kitka** [comment]
Hi! I have the basic DHL plugin called DHL for WooCommerce and another one called DHL WooCommerce Extension (BASIC) - which I think is yours? If I turn the second one on, in the WooCommerce Settings > Shipping screen, an extra link appears called DHL Express. So I think it is part of that extension plugin. That is the screen that I can't edit. Any thoughts?

**Comment by shadimanna** [comment]
Ours is "DHL for WooCommerce" not "DHL WooCommerce Extension (BASIC)", so you will need to reach out to them to ask about it.
