### ISSUE TITLE
CN23/CN22 Document generation

### ISSUE THREAD

**Issue by SeraphMcLight** [shadimanna/dhl-logistic-services-for-woocommerce#94]
We've come across a problem where when an address is outside of the EU clicking the Generate Label function will start but just keeps on loading leaving us having to close the tab and reopen, or straight up leave the page.

Is the generation of CN23/CN22 forms active? Did I miss something, or is it a specific setting that I need to check on my end?

**Comment by SeraphMcLight** [comment]
hey @ilyaprogressus,

currently using version 2.8.14 - I haven't tried refreshing the page while it is loading but can try again. In the past it did generate the label but not the CN23 forms.

Sincerely,
Karim

**Comment by shevasa** [comment]
@SeraphMcLight hi!

This plugin does generate only DHL labels, but not CN23 forms.
There is no functionality for creating CN23 forms at this time, so I guess you will need to use another plugin for this!

Best,
Ilya

**Comment by SeraphMcLight** [comment]
Hey @shevasa

thank you very much for your response! Is it something you might include in the future?

Other than that, great plugin. Thanks again.

Sincerely,
Karim
