### ISSUE TITLE
Method is_crossborder_shipment is unaware of EU exceptions

### ISSUE THREAD

**Issue by ed-at-protectli** [shadimanna/dhl-logistic-services-for-woocommerce#97]
The method `PR_DHL_WC::is_crossborder_shipment()` is currently checking if country codes to determine if a shipment is cross-border. This is not an exhaustive check, as there are exceptions where certain countries are in the EU, but certain territories are not. For example, The Canary Islands is a part of Spain (and uses the country code ES), but not a part of the EU. 

This poses an issue when attempting to generate a label for shipment from another EU country (for example, Germany). The current logic just checks that Germany and Spain are in the EU, and thus this is "not" a cross-border shipment. However, per https://www.dhl.de/de/privatkunden/pakete-versenden/weltweit-versenden/land/kanarische-inseln.html , Customs Declaration forms are required.

It appears that `is_crossborder_shipment` needs additional logic to detect these exceptions and handle them appropriately. I've added a PR with a proposed solution that could be expanded with more similar cases.

**Comment by shevasa** [comment]
@ed-at-protectli hi!

Thank you a lot for letting us know about this. You are 100% right, it is probably a logic issue and we will work on it!
Also thank you for your proposed solution, we will have a more detailed look!

Have a great weekend,
Ilya

**Comment by ed-at-protectli** [comment]
> It's odd WC doesn't include it as a country, or as a State/region in Spain. Effectively you cannot choose the Canary Islands.

The provinces of Las Palmas and Santa Cruz de Tenerife are the collective "Canary Islands" and can be discerned by their postal codes being prefixed with 35 or 38. As thus, any Spanish postal code starting with either of these numbers are referring to the EU-exempted area of the Canary Islands.

Adding the Canary Islands as a country to WC does not make sense, as it is not a country. Even if it were added as a country, your plugin would not know how to handle the falsified country code 

Your developer should review this PR once more as it _is_ a custom solution that could be implemented in your software to detect this case properly. Your code does not expose a filter to the response of `PR_DHL_WC::is_crossborder_shipment()`, so it's not really feasible to fix this in a third-party extension that  filters the response.

**Comment by ed-at-protectli** [comment]
It looks like it has been fixed. I've closed my PR as well.
