### ISSUE TITLE
Manually changing the weight will result in an error

### ISSUE THREAD

**Issue by DinserDLUXE** [shadimanna/dhl-logistic-services-for-woocommerce#99]
When I try to change the weight, given by woocommerce, manually it result in an error and I can`t create a label.
for example the system gives me the weight 0.16 and I have to change it to 0.18 the plugin gives me the error:
Please enter a dizimalnumber without 1000-Point.
If I try comma like 0,18 it gives me the error : The weight must be a number

**Comment by ilyaprogressus** [comment]
@DinserDLUXE hi!

Have you updated anything on your server or plugin, or even WordPress or WooCommerce?

Best,
Ilya

**Comment by DinserDLUXE** [comment]
Hi Ilya,
I have this issue kinda 1 week,
I don`t change every time the wheight manually.
It is just for Warenpost International because they charge per 100 grams.
therefore I can`t say when it exactly started.

About updates, yes I do all updates , most of them automatically, so I have no idea which plugin causes this issue.

I will overwatch and double check this week and come back to you with a report on weekend
